FROM python:3.8-slim-buster

ADD . /klatchat_observer
WORKDIR .
RUN apt-get update \
    && apt install build-essential \
    && pip install --upgrade pip  \
    && pip install wheel  \
    && pip install --no-cache-dir -r ./klatchat_observer/requirements.txt

ENV KLATCHAT_OBSERVER_CONFIG config.json

CMD ["klatchat_observer"]
