FROM python:3.8-slim-buster

ADD [^(utils|config.py)]* /chat_server/
WORKDIR .
RUN apt-get update \
    && apt-get install -y \
    && apt install build-essential -y \
    && pip install --upgrade pip  \
    && pip install wheel  \
    && pip install --no-cache-dir -r ./chat_server/requirements.txt

ENV CHATSERVER_CONFIG chat_server/server_config.json
ENV DATABASE_CONFIG chat_server/server_config.json
ENV SERVER_ENV PROD

CMD python -m chat_server
