FROM python:3.8

ADD . /chat_client
WORKDIR .
RUN apt-get update && \
    apt-get install -y \
    gcc \
    python3  \
    python3-dev  \
    && pip install wheel  \
    && pip install .

ENV CHATCLIENT_CONFIG chat_client/client_config.json

CMD ["chat_client"]
