FROM python:3.10-slim-buster

ENV OVOS_CONFIG_BASE_FOLDER neon
ENV OVOS_CONFIG_FILENAME klat.yaml
ENV XDG_CONFIG_HOME /config

COPY . /app/

WORKDIR /app

RUN apt-get update \
    && apt-get install -y \
    && apt install build-essential -y \
    && pip install --upgrade pip  \
    && pip install wheel  \
    && pip install --no-cache-dir -r ./requirements.txt
