FROM python:3.8

ADD . /klatchat_observer
WORKDIR .
RUN apt-get update && \
    apt-get install -y \
    gcc \
    python3  \
    python3-dev  \
    && pip install wheel  \
    && pip install .

ENV CHATSERVER_CONFIG chat_server/server_config.json
ENV DATABASE_CONFIG chat_server/server_config.json
ENV SERVER_ENV PROD

CMD ["klatchat_observer"]
