name: Deploy Images to GHCR

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Authorize Github Token
      run: |
        echo $CR_PAT | docker login ghcr.io -u neongeckocom --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Build Images
      run: |
        cd scripts && bash build_containers.sh
    - name: Push Images
      run: |
        for IMAGE in $IMAGES; do docker tag neon/$IMAGE:latest ghcr.io/neongeckocom/$IMAGE:$VERSION && docker push ghcr.io/neongeckocom/$IMAGE:$VERSION; done
      env:
        IMAGES: klatchat_observer chat_client chat_server
        VERSION: ${{ steps.extract_branch.outputs.branch }}
