name: Deploy Images to GHCR

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Authorize Github Token
      run: |
        echo $CR_PAT | docker login ghcr.io -u NeonGeckoCom --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Build Images
      run: |
        cd scripts && bash build_containers.sh
    - name: Push Klatchat Observer
      run: |
        for IMAGE in $IMAGES; do docker tag neon/$IMAGE:$VERSION ghcr.io/NeonGeckoCom/$IMAGE:$VERSION && docker push ghcr.io/NeonGeckoCom/$IMAGE:$VERSION; done
      env:
        IMAGES: klatchat_observer chat_client chat_server
        VERSION: ${{ github.event.pull_request.base.ref }}
