name: Deploy Images to GHCR

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Images tag'
        required: true
        default: 'dev'
#      images:
#        description: 'Include Images (klatchat_observer|chat_client|chat_server) space-separated'
#        required: false
#        default: klatchat_observer chat_client chat_server

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Authorize Github Token
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u neongeckocom --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get Version
      id: version
      run: |
        VERSION=$(sed "s/a/-a./" <<< $(python setup.py --version))
        echo ::set-output name=version::${VERSION}
    - name: Build Base Image
      run: |
        cd scripts && bash build_base_image.sh -version ${{ steps.version.outputs.version }}
    - name: Build Pyklatchat Images
      run: |
        cd scripts && bash build_pyklatchat_images.sh -version ${{ steps.version.outputs.version }}
    - name: Apply Workflow Dispatch Environments
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
#        echo ${{ github.event.inputs.images }} >> $IMAGES
    - name: Apply Pull Request Environments
      if: github.event_name == 'pull_request'
      run: |
        echo "VERSION=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
#        echo klatchat_observer chat_client chat_server >> $IMAGES
    - name: Apply Push Environments
      if: github.event_name == 'push'
      run: |
        echo "VERSION=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
#        echo klatchat_observer chat_client chat_server >> $IMAGES
    - name: Push Images
      run: |
        for IMAGE in $IMAGES; do
          docker image push ghcr.io/neongeckocom/$IMAGE:${{ steps.version.outputs.version }}
          if [ -n "$VERSION" ]; then
            docker tag ghcr.io/neongeckocom/$IMAGE:${{ steps.version.outputs.version }} ghcr.io/neongeckocom/$IMAGE:$VERSION
            docker image push ghcr.io/neongeckocom/$IMAGE:$VERSION
          fi
        done
      env:
        VERSION: ${{ env.VERSION }}
        IMAGES: pyklatchat_base klatchat_observer chat_client chat_server
