# This workflow will generate a distribution and upload it to PyPI

name: Publish Version Change
on:
  workflow_call:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Increment Version
        run: |
          VER=$(python setup.py --version)
          python version_bump.py -b ${{ github.ref_name }}
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Incremented Version
