name: Run Unit Tests
on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, 3.10 ]
    runs-on: ubuntu-latest
    env:
      PYKLATCHAT_TESTING_CREDENTIALS: ${{ secrets.PYKLATCHAT_TESTING_CREDENTIALS }}
      SERVER_ENV: ${{ secrets.SERVER_ENV }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
      - name: Get Credential
        run: |
          mkdir -p ~/.local/share/neon
          echo $PYKLATCHAT_TESTING_CREDENTIALS > ~/.local/share/neon/credentials.json
      - name: Test DB Utils
        run: |
          pytest tests/test_db_utils.py --doctest-modules --junitxml=tests/db-utils-test-results.xml
      - name: Upload DB Utils test results
        uses: actions/upload-artifact@v2
        with:
          name: db-utils-test-results
          path: tests/db-utils-test-results.xml
      - name: Test SIO
        run: |
          pytest chat_server/tests/test_sio.py --doctest-modules --junitxml=tests/sio-test-results.xml
      - name: Upload SIO test results
        uses: actions/upload-artifact@v2
        with:
          name: sio-test-results
          path: tests/sio-test-results.xml
